### ISSUE TITLE
API error: no songs found

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#138] opened 2024-08-15 10:49 UTC
I'm guessing another parsing problem. The error occurs after searching for "doors" and then pressing enter on the first search result ("The Doors").
![image](https://github.com/user-attachments/assets/f85b114c-3029-4d16-ac5c-e1f02893f986)
[test.json](https://github.com/user-attachments/files/16624384/test.json)

**Comment by matheus-rosagaze** [comment] 2024-08-15 11:17
Yeah, I'm having the same issue.
Open youtui, search for any artist, press enter, then there are no songs to listen.

Dunno exactly how to confirm if this is the error, but I find this:
![image](https://github.com/user-attachments/assets/499eadb3-ba52-4016-972e-5ee26618ff55)

**Comment by nick42d** [comment] 2024-08-15 14:03
> Yeah, I'm having the same issue. Open youtui, search for any artist, press enter, then there are no songs to listen.
> 
> Dunno exactly how to confirm if this is the error, but I find this: ![image](https://private-user-images.githubusercontent.com/166409053/358203464-499eadb3-ba52-4016-972e-5ee26618ff55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzAzMDcsIm5iZiI6MTcyMzczMDAwNywicGF0aCI6Ii8xNjY0MDkwNTMvMzU4MjAzNDY0LTQ5OWVhZGIzLWJhNTItNDAxNi05NzJlLTVlZTI2NjE4ZmY1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMzUzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWIyNzkwNzUzMjZkMDczNTJmODBhN2JmOGNhNTlkMmFiNmZmYzZhMzI4YjkzOTU4OTZjNGM0ZTNmMzJlYjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v5kvsKPKwaUJvtrpN30GpIJZ_bPJQolUXXeYIE-GolE)

Hi there @matheus-rosagaze, it looks like you might be on an older version of youtui. Could you please upgrade to latest version and test again?

**Comment by nick42d** [comment] 2024-08-15 14:24
> I'm guessing another parsing problem. The error occurs after searching for "doors" and then pressing enter on the first search result ("The Doors"). ![image](https://private-user-images.githubusercontent.com/6623103/358197575-f85b114c-3029-4d16-ac5c-e1f02893f986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzA4OTYsIm5iZiI6MTcyMzczMDU5NiwicGF0aCI6Ii82NjIzMTAzLzM1ODE5NzU3NS1mODViMTE0Yy0zMDI5LTRkMTYtYWM1Yy1lMWYwMjg5M2Y5ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTQwMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNjNDNhNDk1NGM3MjhlY2I5ZTFlNTlkZGMwOGRjNTc3ZDE4YjViN2U2N2IwMWYzMTFiODljNDAxMmFjNTYzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XoJlnKsp3fuT28kaBeCInAvM6HELStl9Nuf0faqgEVs) [test.json](https://github.com/user-attachments/files/16624384/test.json)

Hi there @rkratky, thanks for providing the test file :) I can reproduce this using that file. It looks like you don't have the "Add To Library" button, which the API was expecting. I will make the add/remove from library tokens optional in the API.
![image](https://github.com/user-attachments/assets/e0d94991-767e-48be-940f-bef51f37f1f5)

**Comment by nick42d** [comment] 2024-08-15 14:46
Resolved in #139, I'll keep this open briefly for feedback on the other reported issue.

**Comment by rkratky** [comment] 2024-08-16 07:12
@nick42d, thanks. The search problem is resolved, but the log now shows a new API error (no `test.json` generated though):
![image](https://github.com/user-attachments/assets/1ac683c2-70fa-42c3-be9f-929f2ecf691e)
Not sure if it's worth opening a new issue.

**Comment by nick42d** [comment] 2024-08-16 08:45
This looks similar enough, let's keep this one open. It's the same root cause of missing library management buttons. Apologies for missing this, I'll get onto a fix, but please bear with me as I'll first scan to see if there is anywhere else that this might occur.

**Comment by nick42d** [comment] 2024-08-16 08:56
Resolved in #140

**Comment by rkratky** [comment] 2024-08-16 09:46
Confirming fixed.

**Closed** 2024-08-16 09:47 UTC
Labels: bug, binary
